name: Update Metadata for GitHub Repository Sheet

on:
  workflow_dispatch:
  schedule:
           # ┌──────────── restricted to minute (0-59)
           # │ ┌────────── restricted to hour (0-23)
           # │ │ ┌──────── restricted to day of month (1-31)
           # │ │ │ ┌────── restricted to month (1-12)
           # │ │ │ │ ┌──── restricted to day of week (0-6, 0=Sunday)
           # │ │ │ │ │    * means doesn't restrict anything
    - cron: "0 9 * * 1" # Runs once every Monday at 9 AM UTC

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Write Google credentials
      run: printf "%s" '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > service_account.json

    - name: Run script
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        GOOGLE_CREDENTIALS_PATH: service_account.json
      run: python export_repos.py